# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17CiOKgLSPrWjWoUUoVYkvsGDuRSLoyfM
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
#
# !pip install scikit-learn matplotlib numpy

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

# Load the diabetes dataset
iris_X, iris_y = load_iris(return_X_y=True)

df_X = pd.DataFrame(iris_X, columns=['col1', 'col2', 'col3', 'col4'])
df_y = pd.DataFrame(iris_y, columns=['target'])

df_final=pd.concat([df_X, df_y], axis=1).head()

df_final.to_csv('data_raw.csv', index=False)
