name: farmers
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
<<<<<<< HEAD
    container: docker://dvcorg/cml-py3:latest

=======
    # container: docker://dvcorg/cml-py3:latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
>>>>>>> 5185299577e3c6626dd604455af33266130966e1
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro 

          git fetch --prune
          dvc metrics diff --show-md master > report.md

          # Add figure to the report
          echo "## Validating results by region"
          cml-publish by_region.png --md >> report.md
          cml-send-comment report.md
